import {StyleSheet} from 'react-native';
import {SIZES, COLORS} from '../../constants';
const styles = StyleSheet.create({
  container: {
    width: SIZES.width,
    height: SIZES.height,
    backgroundColor: '#eee',
    position: 'absolute',
  },
  header: {
    fontSize: 32,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 24,
  },
  bottomSheetDish: {
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'column',
    marginHorizontal: 8,
    marginVertical: 5,
    borderRadius: 5,
    borderColor: '#eee',
    borderWidth: 0.5,
  },
  imageBotSheet: {
    alignSelf: 'center',
    margin: 5,
    width: SIZES.width / 5,
    height: SIZES.width / 5,
    borderRadius: 3,
  },
  nameDishBotSheet: {
    color: 'black',
    margin: 5,
    alignSelf: 'center',
    fontSize: SIZES.h2,
  },
  priceBotSheet: {
    marginHorizontal: 5,
    fontSize: SIZES.h3,
  },
  image: {
    alignSelf: 'center',
    margin: 5,
    width: SIZES.width / 8,
    height: SIZES.width / 8,
    borderRadius: 3,
  },
  nameDish: {
    color: 'black',
    alignSelf: 'center',
    fontSize: SIZES.h5,
    fontWeight: 'bold',
  },
  price: {
    alignSelf: 'center',
    fontSize: SIZES.h5,
  },
  tableItem: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: SIZES.width * 0.3,
    height: SIZES.width * 0.3,
    marginVertical: 5,
    marginHorizontal: (SIZES.width * 0.1) / 8,
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  containerFlat: {
    marginHorizontal: (SIZES.width * 0.1) / 8,
  },
  textTouch: {
    textAlign: 'center',
    fontSize: SIZES.body2,
    color: COLORS.white,
  },
  modalOrder: {
    flexDirection: 'row',
    width: SIZES.width - 20,
    height: 80,
    marginHorizontal: 10,
    backgroundColor: '#f90',
    position: 'absolute',
    bottom: -100,
    right: 0,
    left: 0,
    borderRadius: 3,
  },
  modalOrder2: {
    flexDirection: 'row',
    width: SIZES.width - 20,
    height: 80,
    marginHorizontal: 10,
    backgroundColor: '#f90',
    position: 'absolute',
    bottom: 150,
    right: 0,
    left: 0,
    borderRadius: 3,
  },
  viewImageOrder: {
    justifyContent: 'center',
    padding: 10,
  },
  imageOrder: {
    alignContent: 'center',
  },
  orderTitle: {
    fontSize: SIZES.body2,
    color: '#fff',
  },
  orderText: {
    fontSize: SIZES.body3,
    color: '#fff',
  },
  cart_container: {
    position: 'absolute',
    width: SIZES.width,
    height: SIZES.height,
    backgroundColor: '#ddd',
  },
  cart_cancel: {
    width: 18,
    height: 18,
    marginHorizontal: 8,
    alignSelf: 'center',
    right: 0,
  },
  cart_viewCancel: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingVertical: 15,
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  cart_title: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
  },
  cart_section1: {
    width: SIZES.width,
    backgroundColor: '#fff',
    marginTop: 10,
  },
  cart_titleSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 15,
  },
  cart_titleListOrder: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
  },
  cart_addTitle: {
    padding: 5,
    backgroundColor: '#FFA54F',
    borderRadius: 5,
    color: '#fff',
  },
  cart_section1_cartItem: {
    flex: 8,
    flexDirection: 'column',
  },
  cart_acceptContainer: {
    flexDirection: 'row',
    width: SIZES.width,
    height: 80,
    backgroundColor: '#f90',
    position: 'absolute',
    bottom: 30,
    right: 0,
    left: 0,
    borderRadius: 3,
  },
  cart_btnPay: {
    flex: 2.5,
    alignSelf: 'center',
    textAlign: 'center',
    textAlignVertical: 'center',
    height: 40,
    marginHorizontal: 10,
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#fff',
    color: '#f90',
    fontWeight: 'bold',
    fontSize: SIZES.body4,
  },
  cart_totalMoney: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 10,
    paddingBottom: 10,
  },
  cart_totalMoney_title: {
    fontSize: SIZES.body2,
    fontWeight: 'bold',
    paddingVertical: 8,
  },
  cart_delete: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 35,
    paddingTop: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    width: 100,
    height: 40,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    marginVertical: 10,
    elevation: 2,
  },
  buttonAccept: {
    backgroundColor: '#f90',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  modalTextInput: {
    borderColor: '#ddd',
    height: 50,
    borderWidth: 0.5,
    width: SIZES.width / 2,
    color: '#000',
  },
  btnView: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  titleModal: {
    fontSize: SIZES.body2,
    alignItems: 'center',
    textAlign: 'center',
  },
});

export default styles;
